
---
# tasks file for lighthouse-role

- name: Install utils
  yum:
    name:
      - nginx
      - git
    state: present
    update_cache: yes

- name: Apply nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644


- name: Clone lighthouse repository
  git:
    repo: "{{ lighthouse_url }}"
    dest: "{{ lighthouse_dir }}"
    version: master

- name: Apply config
  template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  notify: Nginx reload
